### ISSUE TITLE
Is g_shap only built to run for fully connected networks?

### ISSUE THREAD

**Issue by connor11son** [amiratag/DataShapley#11]
I see that when running g_shap, model = ShapNN() as opposed to self.model.

Does this mean that no matter what model family we choose, gshap scores will come from a NN fit on the data? What if I wanted to find the gshap scores for other gradient-based models?

**Comment by tabularML** [comment]
Hi, mode=ShapNN() is used for neural networks and also linear classifiers (logistic regression or multinomial logistic regression by setting hidden_layers=[]). For convolutional neural networks, the CShapNN() model can be utilized. For other gradient-based methods, there's no implementation of gshap available as of now.
