### ISSUE TITLE
Performance graph phenomenon

### ISSUE THREAD

**Issue by anishprasanna** [amiratag/DataShapley#12]
Hi,

Just had a quick inquiry about the results of my performance graph. I am a little confused as to why the accuracy drastically increases at around 75% removed. I saw a similar increase when using logistic regression as well. Any ideas?
![mygraph](https://user-images.githubusercontent.com/55369497/74965385-244e1500-53e3-11ea-9536-9a87159050eb.png)

**Comment by tabularML** [comment]
Hi, what are the number of classes and their balancedness?

**Comment by anishprasanna** [comment]
Hi,

2 classes, and it’s 75% / 25%.

**Comment by tabularML** [comment]
So what's happening is that all data points from the minority class are removed and therefore the trained model is predicting everything as the majority class which means a jump to the classification accuracy of 75. Does that answer your question?

**Comment by anishprasanna** [comment]
Ok yes. Thanks!
