### ISSUE TITLE
Question in TMC

### ISSUE THREAD

**Issue by yangc22** [amiratag/DataShapley#2]
https://github.com/amiratag/DataShapley/blob/7d64ad67f2f40ec07fb9a72fc7a37201487c8af7/DShap.py#L255
Hi,

why do we restart the model when the second conditional flow is met?

Thanks

**Comment by Bee-zest** [comment]
it'll save your data and other stuff in some directory. You should delete them before re-run the code.

**Comment by tabularML** [comment]
It's to force the users to define a restart_model() method if the user is going to use a custom classifier to prevent possible bugs.

**Comment by yangc22** [comment]
got it, thanks so much!
