### ISSUE TITLE
Show performance graph by gradually removing worst values instead of best values

### ISSUE THREAD

**Issue by rbunn80110** [amiratag/DataShapley#8]
The example notebook generates a performance graph by removing the best data points gradually.  I'm trying to figure out how the accuracy changes when the worst performing data points are removed gradually.  I can't seem to figure out where the values of the worst data points are being gradually removed for the chart and then how to do the opposite.

Thanks,

Bob

**Comment by tabularML** [comment]
You can use the same 'performance_plots' method but feed negated values (or use the '_portion_performance' directly).
