### ISSUE TITLE
Wrong Shape in DShap.py/init_score

### ISSUE THREAD

**Issue by skarussel** [amiratag/DataShapley#9]
The following lines (DShap.py: 172/173) intend to append the f1 score of the true output (y_test) and a random classification (rnd_y).  
``` 
rnd_y = np.random.permutation(self.y)
rnd_f1s.append(f1_score(self.y_test, rnd_y))  
```
Since train and test set can differ in length, it must be:

``` 
rnd_y = np.random.permutation(self.y_test)
rnd_f1s.append(f1_score(self.y_test, rnd_y))  
```

Otherwise the code produces a error, because of the different shapes.

**Comment by tabularML** [comment]
Thanks!
